name: QA
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: false
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Tests
        run: go test -covermode=atomic -coverprofile=.coverage.out ./...
      - uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=zoftko
            -Dsonar.projectKey=zoftko_felf-cli
            -Dsonar.test.inclusions=**/*_test.go
            -Dsonar.go.coverage.reportPaths=.coverage.out
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Build
        env:
          CGO_ENABLED: 0
        run: go build -trimpath
      - uses: zoftko/elfwatch-action@main
        with:
          file: felf-cli
          token: ${{ secrets.ELF_WATCH_TOKEN }}
